### ISSUE TITLE
CI for Livelyness

### ISSUE THREAD

**Issue by itsdevbear** [berachain/berachain-local#2]
Add a Github action to check for liveliness of the local network. Run on all 4 types of runners (arm,x86)x(Linux,mac). 

Probably can use testutil/network from the cosmos-sdk. 

Or to prevent intro of a go dependency, just curl in a loop until timeout or block height or let's say 10, is reached.

**Comment by scooprinder** [comment]
Looks like hosted GH does not have a macOS ARM based runner as best I can tell:

`macos-latest` (which is equivalent to `macos-11`:
```
Run uname -a
Darwin Mac-1661721756332.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.1[4](https://github.com/scooprinder/gh-action-test/runs/8061034186?check_suite_focus=true#step:3:5)1.32~1/RELEASE_X86_64 x86_64
```

`macos-12`
```
Run uname -a
Darwin Mac-1661720[4](https://github.com/scooprinder/gh-action-test/runs/8061034089?check_suite_focus=true#step:3:5)80654.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64
```

**Comment by itsdevbear** [comment]
Just rip x86 on mac for now then. 

Can also investigate moving to CircleCI, but I like Gh action for OSS.

**Comment by chapati23** [comment]
yeah, _gh-hosted_ macOS ARM-based runners aren't supported yet. they seem to have launched support for _self-hosted_ apple silicon runners recently tho: https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/

 issues to track for official apple silicon support:

1. Official GH Roadmap https://github.com/github/roadmap/issues/528
2. Runner Images repo https://github.com/actions/runner-images/issues/2187
